branch-defaults:
  serverHost:
    environment: omega-security-contactForm-backend
    group_suffix: null
environment-defaults:
  my-contact-backend-env:
    branch: null
    repository: null
global:
  application_name: omega-backend
  branch: null
  default_ec2_keyname: omega-admin-key
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
