name: Deploy to GitHub Pages

on:
  push:
    branches:
      - pagesPublic  # Passe dies an den Branch an, den du verwendest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .nojekyll file
        run: echo "" > ./public/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public
